### PR TITLE
Fix win_indicator parser to accept zero (compressed by itself)

### PR DESCRIPTION
**Pull request by ytoku**
RFC3284 allows win_indicator to be zero, which means "the target window was compressed by itself without comparing against another data segment".

This situation is caused when the target window does not contain a sequence from the source.

For example:
source: empty file
target: some contents
```
$ touch a
$ echo foo > b
$ xdelta3 encode -f -S none -s a b delta.vcdiff
$ xdelta3 printhdrs delta.vcdiff
VCDIFF version:               0
VCDIFF header size:           11
VCDIFF header indicator:      VCD_APPHEADER 
VCDIFF secondary compressor:  lzma
VCDIFF application header:    b//a/
XDELTA filename (output):     b
XDELTA filename (source):     a
VCDIFF window number:         0
VCDIFF window indicator:      VCD_ADLER32    # <- no VCD_SOURCE, VCD_TARGET
VCDIFF adler32 checksum:      03D1014F
VCDIFF delta encoding length: 14
VCDIFF target window length:  4
VCDIFF data section length:   4
VCDIFF inst section length:   1
VCDIFF addr section length:   0

```

Another example:
target: source + a sequence longer than a window

```
$ perl -e 'print "C"x4096' > c
$ perl -e 'print "C"x4096; print "D"x65536' > d
$ xdelta3 encode -W 65536 -f -S none -s c d delta2.vcdiff
$ xdelta3 printhdrs delta2.vcdiff
VCDIFF version:               0
VCDIFF header size:           11
VCDIFF header indicator:      VCD_APPHEADER 
VCDIFF secondary compressor:  lzma
VCDIFF application header:    d//c/
XDELTA filename (output):     d
XDELTA filename (source):     c
VCDIFF window number:         0
VCDIFF window indicator:      VCD_SOURCE VCD_ADLER32 
VCDIFF adler32 checksum:      2F60F3EE
VCDIFF copy window length:    4096
VCDIFF copy window offset:    0
VCDIFF delta encoding length: 20
VCDIFF target window length:  65536
VCDIFF data section length:   1
VCDIFF inst section length:   7
VCDIFF addr section length:   1

VCDIFF window number:         1
VCDIFF window indicator:      VCD_ADLER32    # <- no VCD_SOURCE, VCD_TARGET
VCDIFF adler32 checksum:      2E3C403D
VCDIFF window at offset:      65536
VCDIFF delta encoding length: 14
VCDIFF target window length:  4096
VCDIFF data section length:   1
VCDIFF inst section length:   3
VCDIFF addr section length:   0
```

### CODE REVIEW

**Comment by chyyran** [comment]
Thanks for your PR, could you add a quick unit test to cover this behaviour?

**Comment by ytoku** [comment]
Hi! I added a test. (and edited previous commit message)

**Comment by chyyran** [comment]
Merged. Pushing release as 4.0.1 later today.

Thanks again!

**Comment by chyyran** [comment]
Published as https://www.nuget.org/packages/VCDiff/4.0.1

**Pull request merged**
